In [1]:
import numpy as np

## 1 生成

In [4]:
np.arange(5)
#np.arange(20)
#np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [47]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [59]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [48]:
x_ticks = np.linspace(-1, 1, 5)
y_ticks = np.linspace(-1, 1, 5)
x, y = np.meshgrid(x_ticks, y_ticks)
print(x_ticks)
print(x)

[-1.  -0.5  0.   0.5  1. ]
[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]


In [2]:
# Construct from list
a = [1, 2]
a = np.array(a)
a

array([1, 2])

In [60]:
print(np.random.randint(7, size=(3, 3)))

[[4 5 2]
 [1 0 4]
 [3 6 0]]


## 2 简单特性

In [49]:
a = np.array([1, 2, 3])

b = np.array([
    [1., 1.],
    [1., 1.]
])

c = np.array([1,2, 3], dtype="int16")

In [50]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int16


In [51]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
2


In [52]:
a = np.array(np.arange(24)).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
b = np.append(a, [5, 6, 7, 8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [54]:
b.reshape((7, 4))
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [55]:
c = np.array(np.arange(24)).reshape((2, 3, 4)) * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [56]:
np.append(a, c, axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

## 3 基本运算

In [3]:
a + 1

array([2, 3])

In [5]:
a + a

array([2, 4])

In [6]:
a * a

array([1, 4])

In [7]:
a ** a

array([1, 4], dtype=int32)

## 4 切片 索引

In [8]:
a = np.array([1, 2, 3, 4])
print(a[0])  

print(a[:2])  # [1 2]

print(a[-2:])  # [3 4]

print(a[:2] + a[-2:]) 

1
[1 2]
[3 4]
[4 6]


In [9]:
a.shape

(4,)

In [11]:
b = a.reshape((2,2))
b

array([[1, 2],
       [3, 4]])

In [13]:
a

array([1, 2, 3, 4])

In [18]:
a = np.array([[1, 2, 3], [7, 8, 9]])
a

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
# 查看形状：
print(a.shape)

# 查看总的元素个数：
print(a.size)

# 查看维数：
print(a.ndim)

# 对于二维数组，可以传入两个数字来索引：
print(a[1, 1])

# 索引一整行内容：
print(a[0])

(2, 3)
6
2
8
[1 2 3]


In [20]:
a = np.array([[0, 1, 2, 3, 4, 5],
               [10, 11, 12, 13, 14, 15],
               [20, 21, 22, 23, 24, 25],
               [30, 31, 32, 33, 34, 35],
               [40, 41, 42, 43, 44, 45],
               [50, 51, 52, 53, 54, 55]])

# 想得到第一行的第 4 和第 5 两个元素：
print(a[0, 3:5])  # [3 4]

# 得到最后两行的最后两列：
print(a[4:, 4:])  # [[44 45][54 55]]

# 得到第三列：
print(a[:, 2])  # [ 2 12 22 32 42 52]

[3 4]
[[44 45]
 [54 55]]
[ 2 12 22 32 42 52]


In [21]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

切片在内存中使用的是引用机制
引用机制意味着，Python并没有为 b 分配新的空间来存储它的值， 而是让 b 指向了 a 所分配的内存空间，因此，改变 b 会改变 a 的值

In [22]:
a = np.array([0, 1, 2, 3, 4])
b = a[2:4]

b

array([2, 3])

In [23]:
b[0] = 10

b

array([10,  3])

In [24]:
a

array([ 0,  1, 10,  3,  4])

In [26]:
# 解决方法是使用copy()方法产生一个复制，这个复制会申请新的内存：
a = np.array([0, 1, 2, 3, 4])
b = a[2:4].copy()
b[0] = 10
print(a, b)

[0 1 2 3 4] [10  3]


In [27]:
from numpy.random import rand

a = rand(10)
a

array([0.6882935 , 0.46167842, 0.1452194 , 0.11707605, 0.81728818,
       0.25430587, 0.61266907, 0.3963672 , 0.89671203, 0.92713327])

In [28]:
a[a>0.5]

array([0.6882935 , 0.81728818, 0.61266907, 0.89671203, 0.92713327])

In [29]:
a = np.array([[0, 1, 2, 3, 4, 5],
           [10, 11, 12, 13, 14, 15],
           [20, 21, 22, 23, 24, 25],
           [30, 31, 32, 33, 34, 35],
           [40, 41, 42, 43, 44, 45],
           [50, 51, 52, 53, 54, 55]])
b = a[:3]
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [30]:
a = np.array([1, 2, 4, 6])
a > 2

array([False, False,  True,  True])

In [31]:
b = np.where(a > 2)
b

(array([2, 3], dtype=int64),)

In [32]:
# 注意到 where 的返回值是一个元组。
index = np.where(a > 2)[0]
print(index)  # [2 3]

# 可以直接用 where 的返回值进行索引：
loc = np.where(a > 2)
b = a[loc]
print(b)  # [4 6]

[2 3]
[4 6]


In [33]:
a = np.array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = np.where(a > 10)
print(loc)  # (array([0, 0, 1, 1]), array([1, 3, 2, 3]))

# 也可以直接用来索引a：
b = a[loc]
print(b)  # [12 20 11 15]

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 2, 3], dtype=int64))
[12 20 11 15]


## 5 迭代器

In [34]:
import numpy as np

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]


In [36]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7


## 6 常用方法

In [105]:
a = np.arange(10).reshape(1,10)
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
a.shape

(1, 10)

In [40]:
np.squeeze(a).shape

(10,)

In [41]:
b = np.array([3, 2, 7, 4, 1])
b.sort()
b

array([1, 2, 3, 4, 7])

In [42]:
b = np.array([2, 3, 1])
b.argsort(axis=-1)  

array([2, 0, 1], dtype=int64)

In [43]:
a = np.array([[4, 1, 3], [2, 1, 5]])
a.clip(0, 2)

array([[2, 1, 2],
       [2, 1, 2]])

In [44]:
a = np.array([1.344, 2.449, 2.558])
b = a.round(decimals=2)
b

array([1.34, 2.45, 2.56])

In [107]:
c = np.array([1,2,3,1])
np.unique(c)

array([1, 2, 3])

In [111]:
np.any(c > 1)

True

In [112]:
np.all(c > 1)

False

## 7 矩阵运算

In [61]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [62]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [63]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [64]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [65]:
c = np.identity(4) # or np.eye(5)
print(np.linalg.det(c))

1.0


In [67]:
np.linalg.eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))

In [75]:
arr1 =  np.random.randint(15, size=(3, 3))
arr2 = np.random.randint(15, size=(3, 3))
arr1,arr2

(array([[10, 14,  8],
        [ 0,  5,  0],
        [11,  7, 11]]),
 array([[ 8,  4, 10],
        [ 2,  0,  3],
        [ 4, 11, 13]]))

In [76]:
arr1.dot(arr2)

array([[140, 128, 246],
       [ 10,   0,  15],
       [146, 165, 274]])

In [77]:
np.dot(arr1, arr2)

array([[140, 128, 246],
       [ 10,   0,  15],
       [146, 165, 274]])

In [78]:
arr1 @ arr2

array([[140, 128, 246],
       [ 10,   0,  15],
       [146, 165, 274]])

In [92]:
arr1 * arr2

array([[ 80,  56,  80],
       [  0,   0,   0],
       [ 44,  77, 143]])

In [80]:
q, r = np.linalg.qr(arr1)
print(q)
print(r)

[[-0.67267279 -0.55413841 -0.49034879]
 [-0.         -0.66268717  0.74889633]
 [-0.73994007  0.50376219  0.44577163]]
[[-14.86606875 -14.59699963 -13.52072316]
 [  0.          -7.54503822   1.10827682]
 [  0.           0.           0.98069758]]


In [81]:
u, s, v = np.linalg.svd(arr1)
print(u)
print(s)
print(v)

[[-0.74396157 -0.47448105 -0.47051983]
 [-0.12347703 -0.5943964   0.79463598]
 [-0.65671501  0.64927703  0.38362057]]
[25.15760859  6.53042381  0.66954838]
[[-0.58286465 -0.62127734 -0.52372059]
 [ 0.36708748 -0.77633208  0.51240149]
 [-0.72492453  0.10640945  0.68055966]]


In [93]:
np.exp(arr1)

array([[2.20264658e+04, 1.20260428e+06, 2.98095799e+03],
       [1.00000000e+00, 1.48413159e+02, 1.00000000e+00],
       [5.98741417e+04, 1.09663316e+03, 5.98741417e+04]])

In [94]:
np.sqrt(arr1)

array([[3.16227766, 3.74165739, 2.82842712],
       [0.        , 2.23606798, 0.        ],
       [3.31662479, 2.64575131, 3.31662479]])

In [116]:
x = np.arange(1, 10).reshape((3, 3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
np.linalg.norm(x)

16.881943016134134

In [118]:
np.linalg.cond(x)

3.813147060626918e+16

In [119]:
np.linalg.matrix_rank(x)

2

## 8 Broadcasting

In [108]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [109]:
vv = np.tile(v, (4, 1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [113]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.hstack((a,b)))

[1 2 3 3 4 5]


In [114]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.vstack((a,b)))

[[1 2 3]
 [3 4 5]]


## 9 统计

In [68]:
stats = np.array([[1, 2, 3], [4, 5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
print(np.min(stats, axis=0))
print(np.min(stats, axis=1))

print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

[1 2 3]
[1 4]
[4 5 6]
[3 6]


In [95]:
np.argmax(stats, axis=1)

array([2, 2], dtype=int64)

In [70]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [71]:
rnd = np.random.randn(4, 2) # random normals in 4x2 array
print(rnd.mean())
print(rnd.std())
print(rnd.argmin()) # index of minimum element
print(rnd.sum())
print(rnd.sum(axis=0)) # sum of columns
print(rnd.sum(axis=1)) # sum of rows

0.8534764047396268
0.7250000774288792
4
6.827811237917015
[4.12846311 2.69934813]
[1.892754   2.31251883 0.45769756 2.16484084]


In [96]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.04234675 0.55368009 0.90984683]


In [100]:
np.std(arr2)

4.254264382017033

In [101]:
np.std(arr2, axis=0)

array([2.49443826, 4.54606057, 4.18993503])

In [102]:
np.var(arr2, axis=0)

array([ 6.22222222, 20.66666667, 17.55555556])

In [103]:
np.cov(arr2)

array([[ 9.33333333,  4.66666667,  0.33333333],
       [ 4.66666667,  2.33333333,  0.16666667],
       [ 0.33333333,  0.16666667, 22.33333333]])

## 10 采样

In [82]:
np.random.seed(123)
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

In [83]:
print(np.random.rand())   

0.6964691855978616


In [84]:
print(np.random.randn(3,3))

[[-0.95209721 -0.74544106  1.73837013]
 [ 0.4064541   0.32210607 -0.05151772]
 [-0.20420096  1.97934843 -1.61930007]]


In [85]:
np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1])

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [86]:
np.random.choice(3, 10)

array([0, 1, 0, 0, 0, 2, 1, 1, 2, 2])

In [87]:
np.random.choice([1,2,3], 10)

array([3, 2, 1, 1, 3, 2, 1, 3, 3, 3])

In [88]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [90]:
np.random.shuffle(arr)
arr

array([2, 9, 5, 0, 6, 7, 4, 3, 1, 8])

In [91]:
np.random.permutation(arr)

array([0, 4, 8, 1, 2, 6, 5, 9, 3, 7])